apiVersion: v1
kind: Service
metadata:
  name: pkcs-core-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: pkcs-core
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
