spring:
  application:
    name: pkcs-ds
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_htFfb4Azc
          jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_htFfb4Azc/.well-known/jwks.json
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

server:
  port: 8082
  netty:
    max-connections: 10000
    io-worker-count: 16

service:
  api:
    version: v1
