spring:
  application:
    name: pkcs-ds
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_htFfb4Azc
          jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_htFfb4Azc/.well-known/jwks.json
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: pkcs-ds-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.pkcs.chess.model.dto.GameDto
        session.timeout.ms: 15000
        heartbeat.interval.ms: 3000
        max.poll.interval.ms: 300000
        request.timeout.ms: 20000
        retries: 5
        retry.backoff.ms: 1000
        enable.auto.commit: true
        auto.commit.interval.ms: 5000
server:
  port: 8082
  netty:
    max-connections: 10000
    io-worker-count: 16

service:
  api:
    version: v1
