# pkcs-ds-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pkcs-ds
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pkcs-ds
  template:
    metadata:
      labels:
        app: pkcs-ds
    spec:
      containers:
        - name: pkcs-ds
          image: pkcs-ds:1.0
          ports:
            - containerPort: 8082
          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: password
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb-svc.mongo.svc.cluster.local:27017/chess?authSource=admin"
