chesscom:
  api:
    base-url: https://api.chess.com/pub

pkcs:
  concurrent-requests:
    max: 100
  api:
    pkcs-ds:
      base-url: ${PKCS_DS_BASE_URL}/api/v1

spring:
  application:
    name: pkcs-core
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_htFfb4Azc
          jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_htFfb4Azc/.well-known/jwks.json

service:
  api:
    version: v1

server:
  port: 8080

cognito:
  token-uri: https://eu-central-1htffb4azc.auth.eu-central-1.amazoncognito.com/oauth2/token
  client-id: 2keqrk2fosob57vb6esti657aj
  client-secret: ${PKCS_OCTA_CLIENT_SECRET}
  scope: default-m2m-resource-server-y3x2yj/read

logging:
  level:
    root: INFO
