name: Build and Push Docker Images to AWS ECR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Configure AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 4. Login to ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin \
            ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # 5. Build project
      - name: Build with Gradle
        run: ./gradlew build

      # 6. Generate auto version
      - name: Generate version tag
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d-%H%M')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 7. Build & push Docker images
      - name: Build and push Docker images
        env:
          VERSION: ${{ steps.version.outputs.version }}
          ECR: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        run: |
          echo "Publishing version: $VERSION"
          
          # ===== PKCS-CORE → pkcs/core =====
          docker build -t core:latest ./PKCS-CORE
          docker tag core:latest $ECR/pkcs/core:latest
          docker tag core:latest $ECR/pkcs/core:$VERSION
          
          docker push $ECR/pkcs/core:latest
          docker push $ECR/pkcs/core:$VERSION
          
          # ===== PKCS-DS → pkcs/ds =====
          docker build -t ds:latest ./PKCS-DS
          docker tag ds:latest $ECR/pkcs/ds:latest
          docker tag ds:latest $ECR/pkcs/ds:$VERSION
          
          docker push $ECR/pkcs/ds:latest
          docker push $ECR/pkcs/ds:$VERSION

      # 8. Print version
      - name: Build & push Docker images
        env:
          VERSION: ${{ steps.version.outputs.version }}
          ECR: ${{ secrets.ECR_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        run: |
          echo "Publishing version $VERSION"
